### ISSUE TITLE
Avro Phonetic is only working with GTK apps in KDE Neon

### ISSUE THREAD

**Issue by apandada1** [sarim/ibus-avro#140]
I installed the `ibus-avro` package from the official repositories, and configured ibus with Avro Phonetic to write Bangla. However, it only works in GTK apps (e.g. Firefox) and does not work in Qt apps like Dolphin, LibreOffice (I have installed the `libreoffice-kde` package, so Libreoffice is behaving like a Qt app.).
Both the packages `ibus-qt4` and `ibus-gtk` are installed in my system.

**Comment by gunnarhj** [comment]
Is the `libqt5gui5` package installed?

Assuming it is, it's an IBus/KDE bug. But so far it has been believed that the issue with Qt is not present on KDE desktops, so it would be valuable if you could add a comment on https://github.com/ibus/ibus/issues/2137 and describe your case there.

**Comment by apandada1** [comment]
Yes, the package `libqt5gui5` is installed. However, my ibus version is 1.5.17, and not 1.5.19 (which is the version in mentioned in the Vietnamese input issue). In that case, should I still add a comment?

**Comment by gunnarhj** [comment]
> However, my ibus version is 1.5.17, and not 1.5.19 (which is the version in mentioned in the Vietnamese input issue). In that case, should I still add a comment?

The issue is caused by a security patch which was backported to stable releases. But 1.5.17 sounds like Ubuntu 18.04, and the patch has been temporarily disabled there. Have you tried to simply update your packages?

    sudo apt update
    sudo apt upgrade

That should update the ibus packages from version `1.5.17-3ubuntu5.1` to `1.5.17-3ubuntu5.2`.

But in any case, even if that would fix it for you, I think it would be good for the IBus maintainer to know that the issue may affect KDE desktops as well.

**Comment by apandada1** [comment]
I am already using version `1.5.17-3ubuntu5.2`. The issue is still present.

**Comment by gunnarhj** [comment]
Really? In that case your issue is something else. Probably a KDE Neon thing.

(Sorry for leading you to post unnecessarily on the other bug. Can you please post another comment and mention that your issue is caused by something else but the security patch.)

**Comment by apandada1** [comment]
KDE Neon is just Ubuntu 18.04 with latest KDE apps. Is there any way to downgrade/upgrade to another version of ibus which is known not to contain this bug? Then I can test whether this is KDE Neon only.

**Comment by gunnarhj** [comment]
Well, given what we know now I don't know what "this bug" is. Since you have version `1.5.17-3ubuntu5.2`, it's not what I wrongly assumed it was, i.e. the IBus security patch. (Btw, you did relogin after the upgrade to `1.5.17-3ubuntu5.2`, right?)

As you may have noticed, there are quite a few comments on https://github.com/ibus/ibus/issues/2137, but the issue is still not resolved. During the investigation it has been noticed that Qt doesn't talk with IBus / D-Bus as GTK apps do.

So I'm not able to advise you on how to proceed. Changing to some more recent IBus version may or may not help, but due to dependencies I can't tell if testing it on your install would be easily accomplished.

If KDE Neon has a bug tracker, that would probably be a proper place to report the issue.

AFAICT it's unlikely that the issue is specific to `ibus-avro`.

**Comment by sauravgo** [comment]
1. Open $HOME/.xprofile 
2. Add the line --- export QT_IM_MODULE=ibus
log off and log in ... 
It works for me !

**Comment by apandada1** [comment]
@sauravgo Did not work for me. What is the version of Ubuntu you are running?

**Comment by apandada1** [comment]
I can confirm that this was fixed after the last week's update to KDE Neon 5.19.3
